#!/usr/bin/env bash
# bootstrap.sh — Agent-agnostic harness bootstrapper
#
# Works with ANY AI coding agent (Claude, Codex, Cursor, Copilot, Windsurf, etc.)
# or can be run manually by a human.
#
# Usage:
#   From inside the target repo:
#     curl -sL https://raw.githubusercontent.com/ryanhaqueIT/harness-engineering-template/master/bootstrap.sh | bash
#
#   Or if you have the template cloned:
#     bash /path/to/harness-engineering-template/bootstrap.sh
#
#   With a specific target:
#     HARNESS_TARGET=/path/to/my-project bash bootstrap.sh
#
# What it does:
#   1. Clones the harness template to ~/.harness (if not present)
#   2. Copies all static scripts into the target repo
#   3. Creates directory structure
#   4. Prints instructions for the agent to complete the intelligent parts
#
# The mechanical parts (copying files, creating dirs) are handled by this script.
# The intelligent parts (analyzing architecture, writing AGENTS.md, configuring
# import rules) are left to the agent — it reads the playbooks and finishes the job.

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

HARNESS_REPO="https://github.com/ryanhaqueIT/harness-engineering-template.git"
HARNESS_DIR="${HARNESS_HOME:-$HOME/.harness}"
TARGET="${HARNESS_TARGET:-$(pwd)}"

echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo -e "${BOLD} Harness Engineering Bootstrap${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Target: ${CYAN}${TARGET}${NC}"
echo ""

# ─── Step 0: Get the harness template ─────────────────────────────────

if [ -d "$HARNESS_DIR" ]; then
    echo -e "  ${GREEN}Found${NC} harness template at ${HARNESS_DIR}"
    echo "  Pulling latest..."
    git -C "$HARNESS_DIR" pull --ff-only 2>/dev/null || true
else
    echo "  Cloning harness template..."
    git clone "$HARNESS_REPO" "$HARNESS_DIR"
    echo -e "  ${GREEN}Cloned${NC} to ${HARNESS_DIR}"
fi
echo ""

# ─── Step 1: Create directory structure ───────────────────────────────

echo -e "${BOLD}Creating directories...${NC}"

dirs=(
    "scripts"
    ".harness"
    ".claude/commands"
    ".claude/hooks"
    "docs/design-docs"
    "docs/exec-plans/active"
    "docs/exec-plans/completed"
    "docs/product-specs"
    "docs/references"
    "docs/generated"
    "agents"
    "observability"
)

for dir in "${dirs[@]}"; do
    mkdir -p "${TARGET}/${dir}"
done
echo -e "  ${GREEN}Done${NC} — ${#dirs[@]} directories"
echo ""

# ─── Step 2: Copy static scripts ─────────────────────────────────────

echo -e "${BOLD}Copying scripts...${NC}"

COPIED=0
SKIPPED=0

copy_file() {
    local src="$1"
    local dst="$2"
    local label="$3"

    if [ ! -f "$src" ]; then
        return
    fi

    if [ -f "$dst" ] && ! grep -q "Generated by harness-engineering-bootstrap" "$dst" 2>/dev/null; then
        echo -e "  ${YELLOW}SKIP${NC}  ${label} (user-modified)"
        ((SKIPPED++))
    else
        cp "$src" "$dst"
        echo -e "  ${GREEN}COPY${NC}  ${label}"
        ((COPIED++))
    fi
}

# Static scripts (no configuration needed)
for script in check_features.py check_features.sh playwright_gate.py check_ui_playwright.sh \
              check_observability.sh query_logs.sh query_metrics.sh ratchet.py \
              harness_scorecard.py review_pr.sh screenshot_baseline.sh track_quality.sh \
              harness_dashboard.py dashboard_hooks.sh dashboard.sh; do
    copy_file "${HARNESS_DIR}/scripts/${script}" "${TARGET}/scripts/${script}" "scripts/${script}"
done

# Scripts that need agent configuration (copied as starting point)
for script in validate.sh boot_worktree.sh check_ui_legibility.sh check_e2e_deployed.sh; do
    copy_file "${HARNESS_DIR}/scripts/${script}" "${TARGET}/scripts/${script}" "scripts/${script}"
done

echo ""
echo -e "${BOLD}Copying Claude Code integration...${NC}"

# Hooks
copy_file "${HARNESS_DIR}/.claude/hooks/pre-commit.sh" "${TARGET}/.claude/hooks/pre-commit.sh" ".claude/hooks/pre-commit.sh"
copy_file "${HARNESS_DIR}/.claude/hooks/post-edit.sh" "${TARGET}/.claude/hooks/post-edit.sh" ".claude/hooks/post-edit.sh"
copy_file "${HARNESS_DIR}/.claude/hooks/pipeline-tracker.py" "${TARGET}/.claude/hooks/pipeline-tracker.py" ".claude/hooks/pipeline-tracker.py"
copy_file "${HARNESS_DIR}/.claude/hooks/agent-tracker.py" "${TARGET}/.claude/hooks/agent-tracker.py" ".claude/hooks/agent-tracker.py"

# Commands
for cmd in validate.md scorecard.md features.md ratchet.md review.md plan.md morning-check.md entropy.md dashboard.md; do
    copy_file "${HARNESS_DIR}/.claude/commands/${cmd}" "${TARGET}/.claude/commands/${cmd}" ".claude/commands/${cmd}"
done

echo ""
echo -e "${BOLD}Copying documentation...${NC}"

# Docs
for doc in QUALITY_SCORE.md SECURITY.md RELIABILITY.md DESIGN.md FRONTEND.md PRODUCT_SENSE.md; do
    copy_file "${HARNESS_DIR}/docs/${doc}" "${TARGET}/docs/${doc}" "docs/${doc}"
done
copy_file "${HARNESS_DIR}/docs/design-docs/core-beliefs.md" "${TARGET}/docs/design-docs/core-beliefs.md" "docs/design-docs/core-beliefs.md"
copy_file "${HARNESS_DIR}/docs/exec-plans/tech-debt-tracker.md" "${TARGET}/docs/exec-plans/tech-debt-tracker.md" "docs/exec-plans/tech-debt-tracker.md"
copy_file "${HARNESS_DIR}/PLANS.md" "${TARGET}/PLANS.md" "PLANS.md"

# Agents
for agent in planner.md reviewer.md entropy-cleaner.md; do
    copy_file "${HARNESS_DIR}/agents/${agent}" "${TARGET}/agents/${agent}" "agents/${agent}"
done

# Observability
copy_file "${HARNESS_DIR}/docker-compose.observability.yml" "${TARGET}/docker-compose.observability.yml" "docker-compose.observability.yml"
copy_file "${HARNESS_DIR}/observability/vector.toml" "${TARGET}/observability/vector.toml" "observability/vector.toml"

echo ""
echo -e "  ${COPIED} files copied, ${SKIPPED} skipped (user-modified)"
echo ""

# ─── Step 3: Append to .gitignore ────────────────────────────────────

GITIGNORE="${TARGET}/.gitignore"
HARNESS_ENTRIES="# Harness engineering
.harness/snapshots/
instance-metadata.json
*.pid"

if [ -f "$GITIGNORE" ]; then
    if ! grep -q "Harness engineering" "$GITIGNORE" 2>/dev/null; then
        echo "" >> "$GITIGNORE"
        echo "$HARNESS_ENTRIES" >> "$GITIGNORE"
        echo -e "  ${GREEN}Appended${NC} harness entries to .gitignore"
    fi
else
    echo "$HARNESS_ENTRIES" > "$GITIGNORE"
    echo -e "  ${GREEN}Created${NC} .gitignore"
fi
echo ""

# ─── Step 4: Report what still needs the agent ───────────────────────

echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo -e "${BOLD} Bootstrap Complete — Mechanical Parts Done${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${GREEN}✓${NC} Directory structure created"
echo -e "  ${GREEN}✓${NC} Static scripts copied (${COPIED} files)"
echo -e "  ${GREEN}✓${NC} Claude Code commands and hooks installed"
echo -e "  ${GREEN}✓${NC} Documentation templates copied"
echo -e "  ${GREEN}✓${NC} Observability stack copied"
echo ""
echo -e "${YELLOW}  The following require an AI agent to complete:${NC}"
echo ""
echo "  1. scripts/check_imports.py — RULES dict must be configured"
echo "     (Agent reads playbooks/01-analyze.md to derive import rules)"
echo ""
echo "  2. scripts/check_architecture.py — Constants must be configured"
echo "     (DB_MODULE, DB_IMPORT_PATTERNS, AI patterns, TESTABLE_MODULES)"
echo ""
echo "  3. AGENTS.md — Must be written with project-specific content"
echo "     (THE RULE, module deps, golden principles, boundaries)"
echo ""
echo "  4. CLAUDE.md + .github/copilot-instructions.md — Synced with AGENTS.md"
echo ""
echo "  5. .claude/settings.json — Permissions must match detected stack"
echo ""
echo "  6. .harness/feature_list.json — Must be seeded from discovered endpoints"
echo ""
echo "  7. .github/workflows/ — CI must be adapted for detected stack"
echo ""
echo -e "${BOLD}  Next step:${NC} Open this repo in your AI coding agent and say:"
echo ""
echo -e "    ${CYAN}\"Read ~/.harness/playbooks/01-analyze.md and complete the${NC}"
echo -e "    ${CYAN} harness setup for this project. The mechanical parts are${NC}"
echo -e "    ${CYAN} already done — configure the remaining scripts and write${NC}"
echo -e "    ${CYAN} AGENTS.md.\"${NC}"
echo ""
echo -e "  Or if using Claude Code: ${CYAN}/bootstrap${NC}"
echo ""
echo -e "${BOLD}  Live Dashboard:${NC} Watch gates execute in real-time"
echo -e "    ${CYAN}bash scripts/dashboard.sh${NC}  (or ${CYAN}/dashboard${NC} in Claude Code)"
echo ""
echo -e "  Playbooks: ${HARNESS_DIR}/playbooks/"
echo ""
