#!/usr/bin/env python3
# Generated by harness-engineering-bootstrap
"""check_features_live.py — Mechanically execute feature steps against the running app.

Boots the app (or uses a running instance), then for each feature in
.harness/feature_list.json, executes the steps as real HTTP requests
and browser actions. Asserts responses match expected values.

This is the bridge between PRD requirements and mechanical verification.
The agent implementing the code cannot change the feature steps — they
are the contract defined from the PRD before implementation begins.

Based on: Anthropic feature list pattern + OpenAI CDP verification loop.

Usage:
  python scripts/check_features_live.py                    # Run all features
  python scripts/check_features_live.py --category ui      # UI features only
  python scripts/check_features_live.py --category functional  # API features only
  python scripts/check_features_live.py --id F010          # Single feature
  python scripts/check_features_live.py --dry-run          # Show what would execute
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

# ═══════════════════════════════════════════════════
# Color output
# ═══════════════════════════════════════════════════

GREEN = "\033[0;32m"
RED = "\033[0;31m"
YELLOW = "\033[1;33m"
CYAN = "\033[0;36m"
BOLD = "\033[1m"
DIM = "\033[2m"
NC = "\033[0m"


def c(code: str, text: str) -> str:
    if not (hasattr(sys.stdout, "isatty") and sys.stdout.isatty()):
        return text
    return f"{code}{text}{NC}"


# ═══════════════════════════════════════════════════
# HTTP client (no external dependencies)
# ═══════════════════════════════════════════════════


class Response:
    """Simple HTTP response wrapper."""

    def __init__(self, status: int, body: str, headers: dict):
        self.status = status
        self.body = body
        self.headers = headers
        self._json = None

    def json(self) -> dict | list | None:
        if self._json is None:
            try:
                self._json = json.loads(self.body)
            except (json.JSONDecodeError, ValueError):
                self._json = None
        return self._json


def http_request(
    method: str,
    url: str,
    body: dict | None = None,
    headers: dict | None = None,
    timeout: int = 10,
) -> Response:
    """Send an HTTP request using only stdlib."""
    req_headers = {"Content-Type": "application/json", "Accept": "application/json"}
    if headers:
        req_headers.update(headers)

    data = json.dumps(body).encode("utf-8") if body else None
    req = urllib.request.Request(url, data=data, headers=req_headers, method=method)

    try:
        resp = urllib.request.urlopen(req, timeout=timeout)
        resp_body = resp.read().decode("utf-8", errors="replace")
        resp_headers = dict(resp.headers)
        return Response(resp.status, resp_body, resp_headers)
    except urllib.error.HTTPError as e:
        resp_body = e.read().decode("utf-8", errors="replace") if e.fp else ""
        return Response(e.code, resp_body, dict(e.headers))
    except Exception as e:
        return Response(0, str(e), {})


# ═══════════════════════════════════════════════════
# Step parser and executor
# ═══════════════════════════════════════════════════


class StepContext:
    """Carries state across steps within a single feature."""

    def __init__(self, backend_url: str, frontend_url: str):
        self.backend_url = backend_url
        self.frontend_url = frontend_url
        self.last_response: Response | None = None
        self.last_json: dict | list | None = None
        self.stored_values: dict[str, str] = {}
        self.auth_token: str | None = None


def resolve_value(text: str, ctx: StepContext) -> str:
    """Replace {response.field} placeholders with actual values."""

    def replacer(match: re.Match) -> str:
        path = match.group(1)
        parts = path.split(".")
        obj = ctx.last_json
        for part in parts:
            if obj is None:
                return match.group(0)
            if isinstance(obj, dict):
                obj = obj.get(part)
            elif isinstance(obj, list) and part.isdigit():
                obj = obj[int(part)]
            else:
                return match.group(0)
        return str(obj) if obj is not None else match.group(0)

    return re.sub(r"\{response\.([^}]+)\}", replacer, text)


def parse_json_body(text: str) -> dict | None:
    """Extract JSON body from step text."""
    match = re.search(r"with body:\s*(\{.*\})\s*$", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    match = re.search(r"with\s+(\{.*\})\s*$", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    return None


def extract_path(text: str) -> str:
    """Extract URL path from step text."""
    match = re.search(r"(?:GET|POST|PUT|PATCH|DELETE)\s+(/\S+)", text)
    if match:
        return match.group(1)
    match = re.search(r"(/api/\S+|/health\S*|/\S+)", text)
    if match:
        return match.group(1)
    return "/"


def execute_step(step: str, ctx: StepContext) -> tuple[bool, str]:
    """Execute a single feature step. Returns (passed, message)."""

    step = resolve_value(step, ctx)
    sl = step.lower().strip()

    # ── Send HTTP request ─────────────────────────────
    send_match = re.match(
        r"send\s+(GET|POST|PUT|PATCH|DELETE)\s+(/\S+)", step, re.IGNORECASE
    )
    if send_match:
        method = send_match.group(1).upper()
        path = send_match.group(2)
        body = parse_json_body(step)
        url = f"{ctx.backend_url}{path}"

        headers = {}
        if ctx.auth_token:
            headers["Authorization"] = f"Bearer {ctx.auth_token}"

        ctx.last_response = http_request(method, url, body=body, headers=headers)
        ctx.last_json = ctx.last_response.json()

        return True, f"{method} {path} → HTTP {ctx.last_response.status}"

    # ── Verify HTTP status ────────────────────────────
    status_match = re.match(r"verify\s+http\s+(\d+)", sl)
    if status_match:
        expected = int(status_match.group(1))
        if ctx.last_response is None:
            return False, "No preceding request"
        actual = ctx.last_response.status
        if actual == expected:
            return True, f"HTTP {actual} == {expected}"
        return False, f"HTTP {actual} != {expected}"

    # ── Verify response field equals value ────────────
    equals_match = re.match(
        r"verify\s+response\.(\S+)\s+equals?\s+(.+)", step, re.IGNORECASE
    )
    if equals_match:
        field_path = equals_match.group(1)
        expected_raw = equals_match.group(2).strip().strip("'\"")

        obj = ctx.last_json
        for part in field_path.split("."):
            if obj is None:
                return False, f"response.{field_path} is null"
            if isinstance(obj, dict):
                obj = obj.get(part)
            elif isinstance(obj, list) and part.isdigit():
                idx = int(part)
                obj = obj[idx] if idx < len(obj) else None
            else:
                return False, f"Cannot traverse response.{field_path}"

        # Type-aware comparison
        if obj is None:
            return False, f"response.{field_path} is null, expected {expected_raw}"

        try:
            expected_num = float(expected_raw)
            if abs(float(obj) - expected_num) < 0.001:
                return True, f"response.{field_path} = {obj} == {expected_raw}"
            return False, f"response.{field_path} = {obj} != {expected_raw}"
        except (ValueError, TypeError):
            pass

        if str(obj) == expected_raw:
            return True, f"response.{field_path} = {obj}"
        return False, f"response.{field_path} = {obj} != {expected_raw}"

    # ── Verify response field is not null ─────────────
    not_null_match = re.match(
        r"verify\s+response\.(\S+)\s+is\s+not\s+null", step, re.IGNORECASE
    )
    if not_null_match:
        field_path = not_null_match.group(1)
        obj = ctx.last_json
        for part in field_path.split("."):
            if obj is None:
                return False, f"response.{field_path} is null"
            if isinstance(obj, dict):
                obj = obj.get(part)
            elif isinstance(obj, list) and part.isdigit():
                obj = obj[int(part)] if int(part) < len(obj) else None
            else:
                break
        if obj is not None:
            return True, f"response.{field_path} = {obj} (not null)"
        return False, f"response.{field_path} is null"

    # ── Verify response field contains text ───────────
    contains_match = re.match(
        r"verify\s+response\.?(\S*)\s+contains?\s+['\"]?(.+?)['\"]?\s*$",
        step,
        re.IGNORECASE,
    )
    if contains_match:
        field_path = contains_match.group(1)
        expected_text = contains_match.group(2).strip("'\"")

        if field_path:
            obj = ctx.last_json
            for part in field_path.split("."):
                if isinstance(obj, dict):
                    obj = obj.get(part)
                else:
                    obj = None
                    break
            source = str(obj) if obj else ""
        else:
            source = ctx.last_response.body if ctx.last_response else ""

        if expected_text in source:
            return True, f"Contains '{expected_text}'"
        return False, f"Does not contain '{expected_text}'"

    # ── Verify response field has length N ────────────
    length_match = re.match(
        r"verify\s+response\.(\S+)\s+has\s+length\s+(\d+)", step, re.IGNORECASE
    )
    if length_match:
        field_path = length_match.group(1)
        expected_len = int(length_match.group(2))
        obj = ctx.last_json
        for part in field_path.split("."):
            if isinstance(obj, dict):
                obj = obj.get(part)
            elif isinstance(obj, list) and part.isdigit():
                obj = obj[int(part)]
            else:
                obj = None
                break
        if obj is None:
            return False, f"response.{field_path} is null"
        actual_len = len(obj) if hasattr(obj, "__len__") else 0
        if actual_len == expected_len:
            return True, f"response.{field_path} has length {actual_len}"
        return False, f"response.{field_path} has length {actual_len}, expected {expected_len}"

    # ── Authenticate ──────────────────────────────────
    auth_match = re.match(r"authenticate\s+as\s+(\S+)", sl)
    if auth_match or "login" in sl or "authenticate" in sl:
        # Try common auth patterns
        for auth_path in ["/api/auth/login", "/auth/login", "/login", "/api/login"]:
            resp = http_request(
                "POST",
                f"{ctx.backend_url}{auth_path}",
                body={"email": "test@test.com", "password": "testpass"},
            )
            if resp.status == 200 and resp.json():
                token = (resp.json() or {}).get(
                    "access_token", (resp.json() or {}).get("token")
                )
                if token:
                    ctx.auth_token = token
                    return True, f"Authenticated via {auth_path}"
        return False, "Could not authenticate (no auth endpoint responded)"

    # ── Store value ───────────────────────────────────
    store_match = re.match(
        r"store\s+response\.(\S+)\s+as\s+(\S+)", step, re.IGNORECASE
    )
    if store_match:
        field = store_match.group(1)
        var_name = store_match.group(2)
        obj = ctx.last_json
        for part in field.split("."):
            if isinstance(obj, dict):
                obj = obj.get(part)
            else:
                obj = None
                break
        if obj is not None:
            ctx.stored_values[var_name] = str(obj)
            return True, f"Stored {var_name} = {obj}"
        return False, f"response.{field} is null"

    # ── Wait ──────────────────────────────────────────
    wait_match = re.match(r"wait\s+(\d+)", sl)
    if wait_match:
        ms = int(wait_match.group(1))
        time.sleep(ms / 1000)
        return True, f"Waited {ms}ms"

    # ── Unknown step — skip ───────────────────────────
    return True, f"SKIP (unrecognized step)"


# ═══════════════════════════════════════════════════
# Feature execution
# ═══════════════════════════════════════════════════


def execute_feature(
    feature: dict, backend_url: str, frontend_url: str, dry_run: bool = False
) -> tuple[bool, list[tuple[str, bool, str]]]:
    """Execute all steps for a feature. Returns (all_passed, step_results)."""

    ctx = StepContext(backend_url, frontend_url)
    results: list[tuple[str, bool, str]] = []
    all_passed = True

    for step in feature.get("steps", []):
        if dry_run:
            results.append((step, True, "DRY RUN"))
            continue

        try:
            passed, msg = execute_step(step, ctx)
            results.append((step, passed, msg))
            if not passed:
                all_passed = False
        except Exception as e:
            results.append((step, False, f"ERROR: {e}"))
            all_passed = False

    return all_passed, results


# ═══════════════════════════════════════════════════
# Playwright delegation for UI features
# ═══════════════════════════════════════════════════


def execute_ui_feature_playwright(
    feature: dict, frontend_url: str
) -> tuple[bool, list[tuple[str, bool, str]]]:
    """Execute UI feature using Playwright (delegates to playwright_gate.py logic)."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return True, [("Playwright import", True, "SKIP (not installed)")]

    results: list[tuple[str, bool, str]] = []
    all_passed = True

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_context(viewport={"width": 1280, "height": 720}).new_page()

        for step in feature.get("steps", []):
            s = step.strip()
            sl = s.lower()

            try:
                if sl.startswith("navigate to"):
                    path = s.split("to", 1)[-1].strip()
                    full = (
                        f"{frontend_url}{path}"
                        if path.startswith("/")
                        else path
                    )
                    page.goto(full, wait_until="networkidle", timeout=15000)
                    results.append((step, True, f"Navigated to {path}"))

                elif sl.startswith("fill"):
                    parts = s.split("with", 1)
                    if len(parts) == 2:
                        selector = parts[0].replace("Fill", "").replace("fill", "").strip()
                        value = parts[1].strip().strip("'\"")
                        page.fill(selector, value)
                        results.append((step, True, f"Filled {selector}"))
                    else:
                        results.append((step, False, "Cannot parse fill step"))
                        all_passed = False

                elif sl.startswith("click"):
                    selector = s.split("click", 1)[-1].strip().strip("'\"")
                    page.click(selector, timeout=5000)
                    results.append((step, True, f"Clicked {selector}"))

                elif "verify page shows" in sl or "verify page contains" in sl:
                    text = s.split("shows" if "shows" in sl else "contains", 1)[-1].strip()
                    try:
                        page.wait_for_selector(f"text={text}", timeout=5000)
                        results.append((step, True, f"Found '{text}'"))
                    except Exception:
                        results.append((step, False, f"Text '{text}' not found on page"))
                        all_passed = False

                elif sl.startswith("verify page contains"):
                    selector = s.split("contains", 1)[-1].strip()
                    try:
                        page.wait_for_selector(selector, timeout=5000)
                        results.append((step, True, f"Found {selector}"))
                    except Exception:
                        results.append((step, False, f"Selector {selector} not found"))
                        all_passed = False

                elif sl.startswith("wait"):
                    ms = int("".join(c for c in s.split()[-1] if c.isdigit()) or "1000")
                    page.wait_for_timeout(ms)
                    results.append((step, True, f"Waited {ms}ms"))

                else:
                    results.append((step, True, "SKIP (unrecognized UI step)"))

            except Exception as e:
                results.append((step, False, f"ERROR: {e}"))
                all_passed = False

        browser.close()

    return all_passed, results


# ═══════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════


def get_app_urls() -> tuple[str, str]:
    """Get URLs from instance-metadata.json or defaults."""
    repo_root = Path(os.environ.get("REPO_ROOT", "."))
    metadata = repo_root / "instance-metadata.json"
    if metadata.exists():
        data = json.loads(metadata.read_text())
        return (
            data.get("backend_url", "http://localhost:8000"),
            data.get("frontend_url", "http://localhost:3000"),
        )
    return (
        os.environ.get("BACKEND_URL", "http://localhost:8000"),
        os.environ.get("FRONTEND_URL", "http://localhost:3000"),
    )


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Execute feature steps against running app")
    parser.add_argument("--category", type=str, help="Filter by category (functional, ui, security, reliability)")
    parser.add_argument("--id", type=str, help="Run a single feature by ID")
    parser.add_argument("--dry-run", action="store_true", help="Show steps without executing")
    parser.add_argument("--summary", action="store_true", help="One-line output for validate.sh")
    args = parser.parse_args()

    repo_root = Path(os.environ.get("REPO_ROOT", "."))
    feature_file = repo_root / ".harness" / "feature_list.json"

    if not feature_file.exists():
        print("SKIP: No .harness/feature_list.json found")
        return 0

    data = json.loads(feature_file.read_text())
    features = data.get("features", [])

    # Filter
    if args.id:
        features = [f for f in features if f.get("id") == args.id]
    elif args.category:
        features = [f for f in features if f.get("category") == args.category]

    if not features:
        print("No matching features found")
        return 0

    backend_url, frontend_url = get_app_urls()

    # Check if backend is reachable
    if not args.dry_run:
        try:
            urllib.request.urlopen(f"{backend_url}/health", timeout=3)
        except Exception:
            if args.summary:
                print("SKIP: App not running")
                return 0
            print(f"App not running at {backend_url}")
            print("Start with: ./scripts/boot_worktree.sh")
            print("Or set BACKEND_URL environment variable")
            return 0

    # Execute
    total_features = len(features)
    passed_features = 0
    failed_features = 0
    skipped_features = 0

    if not args.summary:
        print(c(BOLD, "═══════════════════════════════════════════════════"))
        print(c(BOLD, " Feature Live Test Runner"))
        print(c(BOLD, "═══════════════════════════════════════════════════"))
        print(f"  Backend:  {backend_url}")
        print(f"  Frontend: {frontend_url}")
        print(f"  Features: {total_features}")
        if args.dry_run:
            print(f"  Mode:     DRY RUN")
        print()

    for feature in features:
        fid = feature.get("id", "???")
        desc = feature.get("description", "")
        category = feature.get("category", "unknown")

        if not args.summary:
            print(c(BOLD, f"  [{fid}] {desc}"))
            print(c(DIM, f"         category: {category}"))

        # Route to appropriate executor
        if category == "ui":
            if args.dry_run:
                all_passed = True
                step_results = [(s, True, "DRY RUN") for s in feature.get("steps", [])]
            else:
                all_passed, step_results = execute_ui_feature_playwright(feature, frontend_url)
        else:
            all_passed, step_results = execute_feature(
                feature, backend_url, frontend_url, dry_run=args.dry_run
            )

        # Report steps
        if not args.summary:
            for step_text, step_passed, step_msg in step_results:
                if step_passed:
                    print(f"    {c(GREEN, 'PASS')}  {step_text}")
                    if step_msg and "SKIP" not in step_msg and "DRY" not in step_msg:
                        print(f"          {c(DIM, step_msg)}")
                else:
                    print(f"    {c(RED, 'FAIL')}  {step_text}")
                    print(f"          {c(RED, step_msg)}")

        if all_passed:
            passed_features += 1
            if not args.summary:
                print(f"    {c(GREEN, '→ FEATURE PASSED')}")

            # Update feature_list.json — flip passes to true
            if not args.dry_run:
                feature["passes"] = True
                feature["verified_by"] = "check_features_live.py"
                feature["verified_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        else:
            failed_features += 1
            if not args.summary:
                print(f"    {c(RED, '→ FEATURE FAILED')}")

        if not args.summary:
            print()

    # Write updated feature list (with passes flipped)
    if not args.dry_run and passed_features > 0:
        data["meta"]["passing"] = sum(1 for f in data["features"] if f.get("passes"))
        feature_file.write_text(json.dumps(data, indent=2) + "\n")

    # Summary
    if args.summary:
        status = "PASS" if failed_features == 0 else "FAIL"
        print(f"Live features: {passed_features}/{total_features} passing — {status}")
        return 0 if failed_features == 0 else 1

    print(c(BOLD, "═══════════════════════════════════════════════════"))
    print(f"  Features: {passed_features} passed, {failed_features} failed ({total_features} total)")
    print(c(BOLD, "═══════════════════════════════════════════════════"))

    if failed_features > 0:
        print(c(RED, "\n  FEATURE TESTS FAILED"))
        print("  Fix the failing features, then run again.")
        return 1
    else:
        print(c(GREEN, "\n  ALL FEATURES VERIFIED"))
        return 0


if __name__ == "__main__":
    sys.exit(main())
